apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  replicas: ES_REPLICAS
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: ES_IMAGE
        # resources:
        #     limits:
        #       cpu: 1000m
        #     requests:
        #       cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cluster
          - name: bootstrap.memory_lock
            value: "false"
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "CLUSTER_LOCATIONS"
          - name: discovery.zen.minimum_master_nodes
            value: "MIN_MASTER_NODES"
          - name: ES_JAVA_OPTS
            value: "-XmsMEM_SIZE -XmxMEM_SIZE"
        # initContainers:
        # - name: fix-permissions
        #   image: busybox
        #   command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        #   securityContext:
        #     privileged: true
        #   volumeMounts:
        #   - name: data
        #     mountPath: /usr/share/elasticsearch/data
        # - name: increase-vm-max-map
        #   image: busybox
        #   command: ["sysctl", "-w", "vm.max_map_count=262144"]
        #   securityContext:
        #     privileged: true
        # - name: increase-fd-ulimit
        #   image: busybox
        #   command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          runAsUser: 1000
        #     privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: STORAGE_CLASS_NAME
      resources:
        requests:
          storage: STORAGE_SIZE
